name: packagename

channels:
    - astropy
    - conda-forge

dependencies:
    - astropy
    - Cython
    - matplotlib
    - numpy
    - reducer
    - notebook
    - photutils
    - ginga
    - astroquery
    - reproject
    - msumastro
    - pillow
    - ipyevents
    - bottleneck
    - astrowidgets
    - gatspy
    - ccdproc
#   - pip:
#       - dependency_from_pip
